bottom_left: !!python/tuple
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAAA4gkA=
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    btu2bdvOhEA=
bottom_right: !!python/tuple
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    t23btm3jh0A=
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAABYhUA=
top_left: !!python/tuple
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    kyRJkiQBhEA=
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    SZIkSZLsgEA=
top_right: !!python/tuple
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    SpIkSZK8iEA=
- !!python/object/apply:numpy.core._multiarray_umath.scalar
  - !!python/object/apply:numpy.dtype
    args: [f8, 0, 1]
    state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
  - !!binary |
    AAAAAABIgUA=
